const ADD_USER = 'ADD_MOVIE';
const CHANGE_STEP = 'CHANGE_STEP'
const ADD_CHILDREN = 'ADD_CHILDREN'
const ADD_COUNTRY = 'ADD_COUNTRY'
const RESET_INFO = 'RESET_INFO'

export { ADD_USER, CHANGE_STEP, ADD_CHILDREN, ADD_COUNTRY, RESET_INFO };